version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEVICE=cpu # Change to cuda if deploying with NVIDIA runtime
      - MAX_FILE_SIZE_MB=50
      - WORKERS=2
    volumes:
      - ./app/models:/app/app/models
      
    # Uncomment below to enable GPU usage in Docker
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
